name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust based on your project

    - name: Run unit tests
      run: |
        # Replace with your actual test command
        python -m unittest discover -s tests -p '*_test.py'

    - name: Archive test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          path/to/your/test/reports
