name: Test, Package, and Deploy

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask matplotlib numpy pytest


      - name: Test with pytest
        run: |
          pytest test_app.py --doctest-modules --junitxml=tests/test-results-${{ matrix.python-version }}.xml > tests/log1.txt 
          pytest test_app.py  > tests/log.txt

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: tests/
        if: ${{ always() }}

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
